version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: fpm
    main: ./cmd/fpm
    binary: fpm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/kartikeyyadav/fpm/internal/cli.Version={{.Version}}

archives:
  - id: fpm
    builds:
      - fpm
    name_template: "fpm-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: Kartikey2011yadav
    name: fpm
  draft: false
  prerelease: auto
