blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/Kartikey2011yadav/fpm#readme
    about: Read the docs before opening an issue
  - name: Discussions
    url: https://github.com/Kartikey2011yadav/fpm/discussions
    about: Ask questions and share ideas
