package env

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type PthLayer struct {
	Name string
	Path string
}

type PthConfig struct {
	Layers []PthLayer
}

const pthFileName = "fpm.pth"

func GeneratePthFile(cfg PthConfig, targetDir string) error {
	if len(cfg.Layers) == 0 {
		return nil
	}

	var b strings.Builder
	b.WriteString("# Generated by fpm — do not edit manually\n")
	b.WriteString("# Path priority: first entry has highest priority\n")

	for _, layer := range cfg.Layers {
		absPath, err := filepath.Abs(layer.Path)
		if err != nil {
			absPath = layer.Path
		}
		fmt.Fprintf(&b, "# [%s]\n", layer.Name)
		fmt.Fprintf(&b, "%s\n", absPath)
	}

	pthPath := filepath.Join(targetDir, pthFileName)
	return os.WriteFile(pthPath, []byte(b.String()), 0644)
}

func RemovePthFile(targetDir string) error {
	pthPath := filepath.Join(targetDir, pthFileName)
	err := os.Remove(pthPath)
	if os.IsNotExist(err) {
		return nil
	}
	return err
}

func ReadPthFile(targetDir string) (*PthConfig, error) {
	pthPath := filepath.Join(targetDir, pthFileName)
	data, err := os.ReadFile(pthPath)
	if err != nil {
		return nil, err
	}

	var layers []PthLayer
	var currentName string

	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		if strings.HasPrefix(line, "# [") && strings.HasSuffix(line, "]") {
			currentName = line[3 : len(line)-1]
			continue
		}
		if strings.HasPrefix(line, "#") {
			continue
		}
		layers = append(layers, PthLayer{
			Name: currentName,
			Path: line,
		})
	}

	return &PthConfig{Layers: layers}, nil
}

func DefaultPthConfig(fpmSitePackages string, globalSitePackages string) PthConfig {
	layers := []PthLayer{
		{Name: "fpm-local", Path: fpmSitePackages},
	}
	if globalSitePackages != "" {
		layers = append(layers, PthLayer{Name: "fpm-global", Path: globalSitePackages})
	}
	return PthConfig{Layers: layers}
}
