package lock

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/BurntSushi/toml"
	"github.com/kartikeyyadav/fpm/internal/pep440"
	"github.com/kartikeyyadav/fpm/internal/resolver"
	"github.com/kartikeyyadav/fpm/pkg/types"
)

const (
	LockVersion  = 1
	LockFileName = "fpm.lock"
)

type Lockfile struct {
	Version        int              `toml:"version"`
	RequiresPython string           `toml:"requires-python,omitempty"`
	GeneratedAt    string           `toml:"generated-at,omitempty"`
	Packages       []LockedPackage  `toml:"package"`
}

type LockedPackage struct {
	Name         string           `toml:"name"`
	Version      string           `toml:"version"`
	Source       PackageSource    `toml:"source"`
	Hashes       []string         `toml:"hashes,omitempty"`
	Dependencies []LockedDep      `toml:"dependencies,omitempty"`
	Markers      string           `toml:"markers,omitempty"`
}

type PackageSource struct {
	Registry string `toml:"registry,omitempty"`
	URL      string `toml:"url,omitempty"`
	Git      string `toml:"git,omitempty"`
	Path     string `toml:"path,omitempty"`
}

type LockedDep struct {
	Name    string `toml:"name"`
	Version string `toml:"version,omitempty"`
}

func Generate(res *resolver.Resolution, requiresPython string) *Lockfile {
	lf := &Lockfile{
		Version:        LockVersion,
		RequiresPython: requiresPython,
	}

	for _, pkg := range res.Packages {
		locked := LockedPackage{
			Name:    pkg.Name.Normalized(),
			Version: pkg.Version.String(),
			Source:  PackageSource{Registry: "https://pypi.org/simple"},
		}

		if pkg.URL != "" {
			locked.Source.URL = pkg.URL
		}
		if pkg.Hash != "" {
			locked.Hashes = []string{"sha256:" + pkg.Hash}
		}

		for _, dep := range pkg.Deps {
			locked.Dependencies = append(locked.Dependencies, LockedDep{
				Name:    dep.Name.Normalized(),
				Version: dep.Specifiers.String(),
			})
		}

		sort.Slice(locked.Dependencies, func(i, j int) bool {
			return locked.Dependencies[i].Name < locked.Dependencies[j].Name
		})

		lf.Packages = append(lf.Packages, locked)
	}

	sort.Slice(lf.Packages, func(i, j int) bool {
		return lf.Packages[i].Name < lf.Packages[j].Name
	})

	return lf
}

func (lf *Lockfile) Write(path string) error {
	dir := filepath.Dir(path)
	tmpFile, err := os.CreateTemp(dir, ".fpm-lock-*.tmp")
	if err != nil {
		return err
	}
	tmpPath := tmpFile.Name()

	fmt.Fprintf(tmpFile, "# This file is generated by fpm. Do not edit manually.\n\n")

	encoder := toml.NewEncoder(tmpFile)
	encoder.Indent = ""
	if err := encoder.Encode(lf); err != nil {
		tmpFile.Close()
		os.Remove(tmpPath)
		return err
	}

	if err := tmpFile.Close(); err != nil {
		os.Remove(tmpPath)
		return err
	}

	return os.Rename(tmpPath, path)
}

func Read(path string) (*Lockfile, error) {
	var lf Lockfile
	_, err := toml.DecodeFile(path, &lf)
	if err != nil {
		return nil, fmt.Errorf("failed to read lockfile: %w", err)
	}
	return &lf, nil
}

type LockfileDiff struct {
	Added   []LockedPackage
	Removed []LockedPackage
	Changed []PackageChange
}

type PackageChange struct {
	Name       string
	OldVersion string
	NewVersion string
}

func Diff(old, new *Lockfile) *LockfileDiff {
	diff := &LockfileDiff{}

	oldMap := make(map[string]LockedPackage)
	for _, p := range old.Packages {
		oldMap[p.Name] = p
	}

	newMap := make(map[string]LockedPackage)
	for _, p := range new.Packages {
		newMap[p.Name] = p
	}

	for name, newPkg := range newMap {
		if oldPkg, exists := oldMap[name]; exists {
			if oldPkg.Version != newPkg.Version {
				diff.Changed = append(diff.Changed, PackageChange{
					Name:       name,
					OldVersion: oldPkg.Version,
					NewVersion: newPkg.Version,
				})
			}
		} else {
			diff.Added = append(diff.Added, newPkg)
		}
	}

	for name, oldPkg := range oldMap {
		if _, exists := newMap[name]; !exists {
			diff.Removed = append(diff.Removed, oldPkg)
		}
	}

	return diff
}

func (d *LockfileDiff) IsEmpty() bool {
	return len(d.Added) == 0 && len(d.Removed) == 0 && len(d.Changed) == 0
}

func (d *LockfileDiff) String() string {
	var b strings.Builder
	for _, p := range d.Added {
		fmt.Fprintf(&b, "+ %s %s\n", p.Name, p.Version)
	}
	for _, p := range d.Removed {
		fmt.Fprintf(&b, "- %s %s\n", p.Name, p.Version)
	}
	for _, c := range d.Changed {
		fmt.Fprintf(&b, "~ %s %s -> %s\n", c.Name, c.OldVersion, c.NewVersion)
	}
	return b.String()
}

func (lf *Lockfile) FindPackage(name string) *LockedPackage {
	normalized := types.NewPackageName(name).Normalized()
	for i := range lf.Packages {
		if lf.Packages[i].Name == normalized {
			return &lf.Packages[i]
		}
	}
	return nil
}

func (lf *Lockfile) ExportRequirementsTxt() string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by fpm\n")
	for _, pkg := range lf.Packages {
		line := fmt.Sprintf("%s==%s", pkg.Name, pkg.Version)
		if len(pkg.Hashes) > 0 {
			for _, h := range pkg.Hashes {
				line += fmt.Sprintf(" \\\n    --hash=%s", h)
			}
		}
		b.WriteString(line + "\n")
	}
	return b.String()
}

func (lf *Lockfile) Versions() map[string]pep440.Version {
	m := make(map[string]pep440.Version)
	for _, pkg := range lf.Packages {
		v, err := pep440.Parse(pkg.Version)
		if err == nil {
			m[pkg.Name] = v
		}
	}
	return m
}
